/**
 * Mapeo centralizado de rutas ES <-> EN.
 * Si agregas una ruta nueva, actualiza SOLO este archivo.
 */
export const ROUTE_MAPPINGS_ES_TO_EN: Record<string, string> = {
  '': 'home',
  'inicio': 'home',
  'nosotros': 'about-us',
  'contacto': 'contact',
  'planes': 'plans',
  'blog': 'blog',
  'aviso-de-privacidad': 'privacy-policy',
  'terminos-y-condiciones': 'terms-and-conditions',
  'apertura-llc': 'llc-opening',
  'renovar-llc': 'llc-renewal',
  'form-apertura-relay': 'relay-opening-form',
  'abre-tu-llc': 'llc-formation',
  'presentacion': 'presentation',
  'apertura-banco-relay': 'relay-account-opening',
  'agendar': 'schedule',
  'fixcal': 'fixcal',
  'abotax': 'abotax',
  'category': 'category',
  'post': 'post',
  'registro-cliente': 'client-register',
  'cuenta-bancaria': 'bank-account',
  'wizard/cuenta-bancaria': 'wizard/bank-account',
};

export const ROUTE_MAPPINGS_EN_TO_ES: Record<string, string> = {
  'home': '',
  'about-us': 'nosotros',
  'contact': 'contacto',
  'plans': 'planes',
  'blog': 'blog',
  'privacy-policy': 'aviso-de-privacidad',
  'terms-and-conditions': 'terminos-y-condiciones',
  'llc-opening': 'apertura-llc',
  'llc-renewal': 'renovar-llc',
  'relay-opening-form': 'form-apertura-relay',
  'llc-formation': 'abre-tu-llc',
  'presentation': 'presentacion',
  'relay-account-opening': 'apertura-banco-relay',
  'schedule': 'agendar',
  'fixcal': 'fixcal',
  'abotax': 'abotax',
  'category': 'category',
  'post': 'post',
  'client-register': 'registro-cliente',
  'bank-account': 'cuenta-bancaria',
  'wizard/bank-account': 'wizard/cuenta-bancaria',
};
