/**
 * Claves permitidas para el resumen de confirmación (alineadas con ServiceFormBuilderService).
 * Filtra datos mezclados de otros servicios o del backend sin afectar el payload guardado.
 */

export const APERTURA_LLC_REVIEW_KEYS: readonly string[] = [
  'llcType',
  'llcName',
  'llcNameOption2',
  'llcNameOption3',
  'businessDescription',
  'llcPhoneNumber',
  'website',
  'llcEmail',
  'linkedin',
  'incorporationState',
  'incorporationDate',
  'hasEin',
  'einNumber',
  'einDocumentUrl',
  'noEinReason',
  'certificateOfFormationUrl',
  'accountType',
  'estadoConstitucion',
  'annualRevenue',
  'actividadFinancieraEsperada',
  'registeredAgentAddress',
  'registeredAgentName',
  'registeredAgentEmail',
  'registeredAgentPhone',
  'registeredAgentType',
  'needsBankVerificationHelp',
  'bankAccountType',
  'bankName',
  'bankAccountNumber',
  'bankRoutingNumber',
  'bankStatementUrl',
  'serviceBillUrl',
  'periodicIncome10k',
  'bankAccountLinkedEmail',
  'bankAccountLinkedPhone',
  'projectOrCompanyUrl',
  'veracityConfirmation',
  'ownerNationality',
  'ownerCountryOfResidence',
  'ownerPersonalAddress',
  'ownerPhoneNumber',
  'ownerEmail',
  'almacenaProductosDepositoUSA',
  'declaroImpuestosAntes',
  'llcConStartCompanies',
  'ingresosMayor250k',
  'activosEnUSA',
  'ingresosPeriodicos10k',
  'contrataServiciosUSA',
  'propiedadEnUSA',
  'tieneCuentasBancarias',
];

export const RENOVACION_LLC_REVIEW_KEYS: readonly string[] = [
  'llcName',
  'state',
  'llcType',
  'mainActivity',
  'hasPropertyInUSA',
  'almacenaProductosDepositoUSA',
  'contrataServiciosUSA',
  'tieneCuentasBancarias',
  'einNumber',
  'countriesWhereLLCDoesBusiness',
  'llcCreationDate',
  'declaracionInicial',
  'declaracionAnoCorriente',
  'cambioDireccionRA',
  'cambioNombre',
  'declaracionAnosAnteriores',
  'agregarCambiarSocio',
  'declaracionCierre',
  'llcOpeningCost',
  'paidToFamilyMembers',
  'paidToLocalCompanies',
  'paidForLLCFormation',
  'paidForLLCDissolution',
  'bankAccountBalanceEndOfYear',
  'totalRevenue2025',
  'hasFinancialInvestmentsInUSA',
  'hasFiledTaxesBefore',
  'wasConstitutedWithStartCompanies',
  'partnersPassportsFileUrl',
  'operatingAgreementAdditionalFileUrl',
  'form147Or575FileUrl',
  'articlesOfOrganizationAdditionalFileUrl',
  'boiReportFileUrl',
  'bankStatementsFileUrl',
];

export const CUENTA_BANCARIA_REVIEW_KEYS: readonly string[] = [
  'businessType',
  'legalBusinessName',
  'industry',
  'numberOfEmployees',
  'briefDescription',
  'websiteOrSocialMedia',
  'einLetterUrl',
  'einNumber',
  'articlesOrCertificateUrl',
  'registeredAgentStreet',
  'registeredAgentUnit',
  'registeredAgentCity',
  'registeredAgentState',
  'registeredAgentZipCode',
  'registeredAgentCountry',
  'incorporationState',
  'incorporationMonthYear',
  'countriesWhereBusiness',
  'validatorMemberId',
  'validatorTitle',
  'validatorIncomeSource',
  'validatorAnnualIncome',
  'validatorFirstName',
  'validatorLastName',
  'validatorDateOfBirth',
  'validatorNationality',
  'validatorCitizenship',
  'validatorPassportNumber',
  'validatorPassportUrl',
  'validatorWorkEmail',
  'validatorPhone',
  'canReceiveSMS',
  'isUSResident',
  'ownerPersonalStreet',
  'ownerPersonalUnit',
  'ownerPersonalCity',
  'ownerPersonalState',
  'ownerPersonalCountry',
  'ownerPersonalPostalCode',
  'serviceBillUrl',
  'isMultiMember',
  'llcType',
];

/** Copia superficial solo con claves permitidas (objetos anidados por referencia). */
export function pickServiceDataForReview(
  data: Record<string, unknown> | null | undefined,
  keys: readonly string[],
): Record<string, unknown> {
  if (!data || typeof data !== 'object') {
    return {};
  }
  const out: Record<string, unknown> = {};
  for (const k of keys) {
    if (Object.prototype.hasOwnProperty.call(data, k)) {
      out[k] = data[k];
    }
  }
  return out;
}
